@extends('layouts.pages')
@section('content')
@include('includes.classes')
@include('includes.appointment')
@include('includes.testimonial')
@endsection
@section('title')
Classes
@endsection
@section('gHeaderT')
Classes
@endsection
@section('gHeaderA')
Classes
@endsection
